Repository caglapickaxe/charlestonbieber, pull requests merged in 2020-05, with the labels that each got.

#3 Dank lyrics
  src/commands/Lyrics.ts
  src/commands/RandomLyrics.ts
Labels: enhancement

#5 Support other database systems
  .env.example
  README.md
  package.json
  src/index.ts
  src/ormConfig.ts
  yarn.lock
Labels: enhancement

#7 Fix help command
  src/commands/Help.ts
Labels: bug, enhancement

#9 Fix bot crashing after disconnect
  src/clients/Mixer.ts
  src/clients/TwitchPubSub.ts
Labels: fix
